Sidebar logic with homepage
Alexander-Lindstroem/vc-group-aadam pull request #10
Opened 2024-11-27 15:08 UTC by DimitarIM

No images yet / Waiting for Adam's homepage structure

2024-11-27 15:10 UTC, Alexander-Lindstroem requested changes

2024-11-27 15:10 UTC, Alexander-Lindstroem commented on js/index.js
> +},
The array of objects should be made using a constructor

2024-11-27 17:38 UTC, DimitarIM commented on js/index.js
> +},
Fixed it

2024-11-28 09:46 UTC, Alexander-Lindstroem approved these changes

2024-12-02 14:11 UTC, Alibaba000101 reviewed
lGTM

2024-12-02 14:11 UTC, Alibaba000101 approved these changes
Look Ok

2024-12-04 09:34 UTC, andre84o approved these changes

2024-12-04 12:04 UTC, Alexander-Lindstroem requested changes
You still need

2024-12-04 12:04 UTC, Alexander-Lindstroem commented on index.html
> +                        <span class="tooltip">Tasmanian Devil</span>
You still need to generate the sidebar HTML from JS according to Rob

2024-12-04 15:39 UTC, closed without merging