Feature/desktop menu
Alexander-Lindstroem/vc-group-aadam pull request #11
Opened 2024-11-29 11:43 UTC by AwdamnKaya

Added a desktop and mobile navigational menu with very basic css.

2024-11-29 12:27 UTC, Alexander-Lindstroem approved these changes
LGTM

2024-11-29 14:31 UTC, DimitarIM requested changes
The menu breaks down after 770px for me. Needs responsiveness to be implemented
![Screenshot 2024-11-29 153044](https://github.com/user-attachments/assets/db11a7fa-348b-4846-ba04-c6211a9e79dc)

2024-12-03 16:41 UTC, DimitarIM approved these changes

2024-12-06 15:07 UTC, Alibaba000101 approved these changes
Nice work chief

2024-12-06 15:07 UTC, Alibaba000101 commented on html/birds.html
> +    <title>Birds</title>
nice

2024-12-10 14:31 UTC, Alexander-Lindstroem approved these changes
LGTM

2024-12-10 14:50 UTC, merged