Feature/mammals objects
Alexander-Lindstroem/vc-group-aadam pull request #18
Opened 2024-12-06 14:12 UTC by AwdamnKaya

created mammals objects and integrated into sidebar

2024-12-06 15:04 UTC, Alibaba000101 approved these changes
Cool

2024-12-06 15:20 UTC, Alexander-Lindstroem requested changes

2024-12-06 15:20 UTC, Alexander-Lindstroem commented on scripts/mammals.js
> +    let activeAnimal = animalButtons.find(b => b.classList.contains("animal-active"));
I would recommend using a more syntactic variable name, but it won't change the outcome of the code so if you don't want to you don't have to.

2024-12-06 19:57 UTC, andre84o approved these changes
LG

2024-12-10 14:31 UTC, Alexander-Lindstroem approved these changes
Good changes.

2024-12-10 15:03 UTC, merged