Created header, CSS and added to general.css
Alexander-Lindstroem/vc-group-aadam pull request #4
Opened 2024-11-25 14:58 UTC by DimitarIM

Above self-explanatory

2024-11-25 15:00 UTC, Alexander-Lindstroem requested changes

2024-11-25 15:00 UTC, Alexander-Lindstroem commented on css/general.css
> +    padding: 0;
move "margin: 0" to body
padding not required.

2024-11-25 15:00 UTC, Alexander-Lindstroem commented on css/general.css
> +    padding: 0;
in body, you can also add min-height: 100%

2024-11-25 20:46 UTC, DimitarIM commented on css/general.css
> +    padding: 0;
Sure, I've committed the changes.

2024-11-26 09:43 UTC, Alexander-Lindstroem approved these changes
LGTM

2024-11-26 09:44 UTC, andre84o approved these changes
looks good

2024-11-26 13:56 UTC, andre84o approved these changes
LG

2024-11-26 15:20 UTC, merged